# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap

destination: /home/sites/blog.wedrop.it

# Site settings
title: "Drop a Blog"
description: > # this means to ignore newlines until "email:"
   I'm a software architect and Free Software hacker

email: sl@mailicio.us
#blog logo
logo: "/assets/images/sl_logo.png"
float_logo: true # true, false (default)

# blog cover
#cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"
cover: "/assets/images/4D936417DC.jpg"

name: 'Sebastian Lauwers'
author: 'Sebastian Lauwers'
author_image: "/assets/images/sl_avatar.jpg"

paginate: 10

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

url: "https://blog.wedrop.it" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@teotwaki'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/teotwaki
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/teotwaki
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
